#21 change yaml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -166,16 +166,16 @@ pages:
     - echo "Processing $FILE.rec"
     - docker run -d -ti --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp:/tmp -v $(pwd)/data:/data --name=replay-$FILE $CI_REGISTRY_IMAGE/video-h264-replay --cid=111 --name=img /data/$FILE.rec
     - |
-      echo "Waiting for /tmp/img to be created by replay-$FILE..."
+      echo "Waiting for System V SHM to be initialized by replay-$FILE..."
       for i in {1..30}; do
-        if docker exec replay-$FILE test -e /tmp/img; then
-          echo "/tmp/img found inside container."
+        if docker exec replay-$FILE ipcs -m | grep -q '0x'; then
+          echo "System V shared memory segment is available."
           break
         fi
         sleep 1
       done
-      if ! docker exec replay-$FILE test -e /tmp/img; then
-        echo "Error: /tmp/img was not created inside the container in time."
+      if ! docker exec replay-$FILE ipcs -m | grep -q '0x'; then
+        echo "Error: Shared memory segment was not created inside the container in time."
         docker logs replay-$FILE
         exit 1
       fi
