#21 change yaml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -168,25 +168,25 @@ pages:
     - |
       echo "Waiting for /tmp/img to be created by replay-$FILE..."
       for i in {1..30}; do
-        if [ -e /tmp/img ]; then
-          echo "/tmp/img found."
+        if docker exec replay-$FILE test -e /tmp/img; then
+          echo "/tmp/img found inside container."
           break
         fi
         sleep 1
       done
-      if [ ! -e /tmp/img ]; then
-        echo "Error: /tmp/img was not created in time."
+      if ! docker exec replay-$FILE test -e /tmp/img; then
+        echo "Error: /tmp/img was not created inside the container in time."
         docker logs replay-$FILE
         exit 1
       fi
     - docker run -d --net=host --ipc=host -e DISPLAY=$DISPLAY -v /tmp:/tmp -v $(pwd)/logs/csv:/opt --name=application-$FILE $CI_REGISTRY_IMAGE/application:latest --cid=111 --name=img --width=640 --height=480 --output=/opt/$FILE.csv
     - while docker ps | grep -q replay-$FILE; do sleep 1; done
     - mkdir -p ./logs/csv/
-    - if [ -f ./logs/csv/$FILE.csv ]; then cp ./logs/csv/$FILE.csv; fi
     - docker inspect -f '{{.State.Status}}' application-$FILE
     - docker logs application-$FILE
     - docker cp application-$FILE:/opt/$FILE.csv ./logs/csv/$FILE.csv
-    - docker stop application-$FILE || true  && docker rm application-$FILE || true
+    - docker stop application-$FILE || true
+    - docker rm application-$FILE || true
 
   artifacts:
     name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-csv"
